// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package docmanagement.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the DocManagement module
	public static void downloadFile(IContext context, docmanagement.proxies.Manage_Docs _download)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("download", _download == null ? null : _download.getMendixObject());
			Core.execute(context, "DocManagement.DownloadFile", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static docmanagement.proxies.AddressEntity getExampleAddress(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "DocManagement.GetExampleAddress", params);
			return result == null ? null : docmanagement.proxies.AddressEntity.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void login_Validation(IContext context, docmanagement.proxies.Login _login)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Login", _login == null ? null : _login.getMendixObject());
			Core.execute(context, "DocManagement.Login_Validation", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean myAfterStartup(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			return (java.lang.Boolean)Core.execute(context, "DocManagement.MyAfterStartup", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void saveDetails(IContext context, docmanagement.proxies.Registration _registration)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Registration", _registration == null ? null : _registration.getMendixObject());
			Core.execute(context, "DocManagement.SaveDetails", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<docmanagement.proxies.Login> session_Maintain(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.List<IMendixObject> objs = Core.execute(context, "DocManagement.Session_Maintain", params);
			java.util.List<docmanagement.proxies.Login> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<docmanagement.proxies.Login>();
				for (IMendixObject obj : objs)
					result.add(docmanagement.proxies.Login.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}