// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package docmanagement.proxies;

public class Manage_Docs extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DocManagement.Manage_Docs";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FIle_Format("FIle_Format"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Manage_Docs_Login("DocManagement.Manage_Docs_Login");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Manage_Docs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DocManagement.Manage_Docs"));
	}

	protected Manage_Docs(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject manage_DocsMendixObject)
	{
		super(context, manage_DocsMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("DocManagement.Manage_Docs", manage_DocsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DocManagement.Manage_Docs");
	}

	/**
	 * @deprecated Use 'Manage_Docs.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static docmanagement.proxies.Manage_Docs initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return docmanagement.proxies.Manage_Docs.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static docmanagement.proxies.Manage_Docs initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new docmanagement.proxies.Manage_Docs(context, mendixObject);
	}

	public static docmanagement.proxies.Manage_Docs load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return docmanagement.proxies.Manage_Docs.initialize(context, mendixObject);
	}

	public static java.util.List<docmanagement.proxies.Manage_Docs> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<docmanagement.proxies.Manage_Docs> result = new java.util.ArrayList<docmanagement.proxies.Manage_Docs>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DocManagement.Manage_Docs" + xpathConstraint))
			result.add(docmanagement.proxies.Manage_Docs.initialize(context, obj));
		return result;
	}

	/**
	 * Set value of FIle_Format
	 * @param file_format
	 */
	public final docmanagement.proxies.FileType getFIle_Format()
	{
		return getFIle_Format(getContext());
	}

	/**
	 * @param context
	 * @return value of FIle_Format
	 */
	public final docmanagement.proxies.FileType getFIle_Format(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.FIle_Format.toString());
		if (obj == null)
			return null;

		return docmanagement.proxies.FileType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of FIle_Format
	 * @param file_format
	 */
	public final void setFIle_Format(docmanagement.proxies.FileType file_format)
	{
		setFIle_Format(getContext(), file_format);
	}

	/**
	 * Set value of FIle_Format
	 * @param context
	 * @param file_format
	 */
	public final void setFIle_Format(com.mendix.systemwideinterfaces.core.IContext context, docmanagement.proxies.FileType file_format)
	{
		if (file_format != null)
			getMendixObject().setValue(context, MemberNames.FIle_Format.toString(), file_format.toString());
		else
			getMendixObject().setValue(context, MemberNames.FIle_Format.toString(), null);
	}

	/**
	 * @return value of Manage_Docs_Login
	 */
	public final docmanagement.proxies.Login getManage_Docs_Login() throws com.mendix.core.CoreException
	{
		return getManage_Docs_Login(getContext());
	}

	/**
	 * @param context
	 * @return value of Manage_Docs_Login
	 */
	public final docmanagement.proxies.Login getManage_Docs_Login(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		docmanagement.proxies.Login result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Manage_Docs_Login.toString());
		if (identifier != null)
			result = docmanagement.proxies.Login.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Manage_Docs_Login
	 * @param manage_docs_login
	 */
	public final void setManage_Docs_Login(docmanagement.proxies.Login manage_docs_login)
	{
		setManage_Docs_Login(getContext(), manage_docs_login);
	}

	/**
	 * Set value of Manage_Docs_Login
	 * @param context
	 * @param manage_docs_login
	 */
	public final void setManage_Docs_Login(com.mendix.systemwideinterfaces.core.IContext context, docmanagement.proxies.Login manage_docs_login)
	{
		if (manage_docs_login == null)
			getMendixObject().setValue(context, MemberNames.Manage_Docs_Login.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Manage_Docs_Login.toString(), manage_docs_login.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final docmanagement.proxies.Manage_Docs that = (docmanagement.proxies.Manage_Docs) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DocManagement.Manage_Docs";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
