// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package docmanagement.proxies;

public class Registration
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject registrationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DocManagement.Registration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		First_Name("First_Name"),
		Last_Name("Last_Name"),
		Phone_Number("Phone_Number"),
		Email("Email"),
		DOB("DOB"),
		Password("Password"),
		User_Id("User_Id");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Registration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DocManagement.Registration"));
	}

	protected Registration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject registrationMendixObject)
	{
		if (registrationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DocManagement.Registration", registrationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DocManagement.Registration");

		this.registrationMendixObject = registrationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Registration.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static docmanagement.proxies.Registration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return docmanagement.proxies.Registration.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static docmanagement.proxies.Registration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("DocManagement.Login", mendixObject.getType()))
			return docmanagement.proxies.Login.initialize(context, mendixObject);

		return new docmanagement.proxies.Registration(context, mendixObject);
	}

	public static docmanagement.proxies.Registration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return docmanagement.proxies.Registration.initialize(context, mendixObject);
	}

	public static java.util.List<? extends docmanagement.proxies.Registration> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<docmanagement.proxies.Registration> result = new java.util.ArrayList<docmanagement.proxies.Registration>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DocManagement.Registration" + xpathConstraint))
			result.add(docmanagement.proxies.Registration.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of First_Name
	 */
	public final java.lang.String getFirst_Name()
	{
		return getFirst_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of First_Name
	 */
	public final java.lang.String getFirst_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.First_Name.toString());
	}

	/**
	 * Set value of First_Name
	 * @param first_name
	 */
	public final void setFirst_Name(java.lang.String first_name)
	{
		setFirst_Name(getContext(), first_name);
	}

	/**
	 * Set value of First_Name
	 * @param context
	 * @param first_name
	 */
	public final void setFirst_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String first_name)
	{
		getMendixObject().setValue(context, MemberNames.First_Name.toString(), first_name);
	}

	/**
	 * @return value of Last_Name
	 */
	public final java.lang.String getLast_Name()
	{
		return getLast_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Last_Name
	 */
	public final java.lang.String getLast_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Last_Name.toString());
	}

	/**
	 * Set value of Last_Name
	 * @param last_name
	 */
	public final void setLast_Name(java.lang.String last_name)
	{
		setLast_Name(getContext(), last_name);
	}

	/**
	 * Set value of Last_Name
	 * @param context
	 * @param last_name
	 */
	public final void setLast_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String last_name)
	{
		getMendixObject().setValue(context, MemberNames.Last_Name.toString(), last_name);
	}

	/**
	 * @return value of Phone_Number
	 */
	public final java.lang.Long getPhone_Number()
	{
		return getPhone_Number(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone_Number
	 */
	public final java.lang.Long getPhone_Number(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Phone_Number.toString());
	}

	/**
	 * Set value of Phone_Number
	 * @param phone_number
	 */
	public final void setPhone_Number(java.lang.Long phone_number)
	{
		setPhone_Number(getContext(), phone_number);
	}

	/**
	 * Set value of Phone_Number
	 * @param context
	 * @param phone_number
	 */
	public final void setPhone_Number(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long phone_number)
	{
		getMendixObject().setValue(context, MemberNames.Phone_Number.toString(), phone_number);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of DOB
	 */
	public final java.util.Date getDOB()
	{
		return getDOB(getContext());
	}

	/**
	 * @param context
	 * @return value of DOB
	 */
	public final java.util.Date getDOB(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DOB.toString());
	}

	/**
	 * Set value of DOB
	 * @param dob
	 */
	public final void setDOB(java.util.Date dob)
	{
		setDOB(getContext(), dob);
	}

	/**
	 * Set value of DOB
	 * @param context
	 * @param dob
	 */
	public final void setDOB(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dob)
	{
		getMendixObject().setValue(context, MemberNames.DOB.toString(), dob);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of User_Id
	 */
	public final java.lang.Long getUser_Id()
	{
		return getUser_Id(getContext());
	}

	/**
	 * @param context
	 * @return value of User_Id
	 */
	public final java.lang.Long getUser_Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.User_Id.toString());
	}

	/**
	 * Set value of User_Id
	 * @param user_id
	 */
	public final void setUser_Id(java.lang.Long user_id)
	{
		setUser_Id(getContext(), user_id);
	}

	/**
	 * Set value of User_Id
	 * @param context
	 * @param user_id
	 */
	public final void setUser_Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long user_id)
	{
		getMendixObject().setValue(context, MemberNames.User_Id.toString(), user_id);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return registrationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final docmanagement.proxies.Registration that = (docmanagement.proxies.Registration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DocManagement.Registration";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
